/**
 * Predefined list of common technical and professional skills for autocomplete.
 * Organized by category but provided as a flat list for easy searching.
 */
export const COMMON_SKILLS: string[] = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'C',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Dart',
  'Scala',
  'R',
  'MATLAB',
  'Perl',
  'Shell Scripting',
  'PowerShell',

  // Frontend Technologies
  'Angular',
  'React',
  'Vue.js',
  'Svelte',
  'HTML',
  'CSS',
  'SCSS',
  'SASS',
  'Less',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'jQuery',
  'Webpack',
  'Vite',
  'Parcel',
  'Rollup',

  // Backend Technologies
  'Node.js',
  'Express.js',
  'NestJS',
  'Spring Boot',
  'Spring Framework',
  'Django',
  'Flask',
  'FastAPI',
  'ASP.NET',
  'ASP.NET Core',
  'Laravel',
  'Symfony',
  'CodeIgniter',
  'Ruby on Rails',
  'Sinatra',
  'Gin',
  'Echo',
  'Fiber',

  // Databases
  'PostgreSQL',
  'MySQL',
  'SQL Server',
  'Oracle',
  'SQLite',
  'MongoDB',
  'Redis',
  'Cassandra',
  'DynamoDB',
  'Elasticsearch',
  'Neo4j',
  'InfluxDB',
  'CouchDB',

  // Cloud Platforms
  'AWS',
  'Microsoft Azure',
  'Google Cloud Platform',
  'IBM Cloud',
  'Digital Ocean',
  'Heroku',
  'Vercel',
  'Netlify',
  'Railway',
  'Cloudflare',

  // DevOps & Tools
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitLab CI',
  'GitHub Actions',
  'CircleCI',
  'Travis CI',
  'Ansible',
  'Terraform',
  'Vagrant',
  'Prometheus',
  'Grafana',
  'ELK Stack',
  'Nagios',
  'Zabbix',

  // Version Control & Collaboration
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'SVN',
  'Mercurial',
  'Jira',
  'Confluence',
  'Slack',
  'Microsoft Teams',
  'Trello',
  'Asana',
  'Notion',

  // Development Tools
  'IntelliJ IDEA',
  'Visual Studio Code',
  'Visual Studio',
  'Eclipse',
  'NetBeans',
  'Sublime Text',
  'Atom',
  'Vim',
  'Emacs',
  'Postman',
  'Insomnia',
  'Swagger',
  'Figma',
  'Adobe XD',
  'Sketch',

  // Build Tools
  'Maven',
  'Gradle',
  'npm',
  'Yarn',
  'pnpm',
  'pip',
  'Composer',
  'NuGet',
  'CMake',
  'Make',
  'Bazel',
  'SBT',

  // Testing
  'Jest',
  'Cypress',
  'Selenium',
  'Playwright',
  'JUnit',
  'TestNG',
  'Mockito',
  'PyTest',
  'PHPUnit',
  'RSpec',
  'Mocha',
  'Chai',
  'Jasmine',
  'Karma',

  // Mobile Development
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  'Cordova',
  'Android Development',
  'iOS Development',
  'Unity',
  'Unreal Engine',

  // Data Science & AI
  'Machine Learning',
  'Deep Learning',
  'Data Science',
  'Data Analysis',
  'Artificial Intelligence',
  'Natural Language Processing',
  'Computer Vision',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Jupyter',
  'Apache Spark',
  'Hadoop',
  'Kafka',

  // Methodologies & Practices
  'Agile',
  'Scrum',
  'Kanban',
  'Test-Driven Development',
  'Behavior-Driven Development',
  'Domain-Driven Design',
  'Microservices',
  'RESTful APIs',
  'GraphQL',
  'gRPC',
  'SOAP',
  'OAuth',
  'JWT',
  'SOLID Principles',
  'Design Patterns',
  'Clean Code',
  'Code Review',
  'Pair Programming',

  // Soft Skills
  'Leadership',
  'Team Management',
  'Project Management',
  'Communication',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  'Mentoring',
  'Public Speaking',
  'Technical Writing',
  'Documentation',
  'Client Relations',
  'Negotiation',
  'Strategic Planning',
  'Risk Management',

  // Industry Specific
  'E-commerce',
  'Fintech',
  'Healthcare',
  'Education Technology',
  'Gaming',
  'Blockchain',
  'Cryptocurrency',
  'IoT',
  'Cybersecurity',
  'Network Security',
  'Penetration Testing',
  'Ethical Hacking',
  'Digital Marketing',
  'SEO',
  'SEM',
  'Social Media Marketing',
  'Content Marketing',
  'UX Design',
  'UI Design',
  'Product Management',
  'Business Analysis',
  'Data Visualization',
  'Business Intelligence',
];
